title: Find the clone
hero_image: images/banner.png
description: Create a game to find a character amongst a sea of other characters.
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: builder, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Introduction
  - title: What you will need
  - title: Import your costumes
  - title: Making a grid
  - title: Testing the script
  - title: Stamping a row